name = toolranks
optional_depends = default, mcl_tools
description = """
Tools gain levels for digging nodes. Higher level tools dig faster and take longer to wear out.
"""

# ContentDB
supported_games = minetest_game, mineclone2, mineclonia, *
min_minetest_version = 0.4.16
